config/routes.rb
Infolegal::Application.routes.draw do
  resources :normas

  resources :lugars

  resources :ambitos

end

app/models/ambito.rb
class Ambito < ActiveRecord::Base
end

app/models/lugar.rb
class Lugar < ActiveRecord::Base
end

app/models/norma.rb
class Norma < ActiveRecord::Base
  has_one :ambito
  has_one :lugar
  
end

app/controllers/ambitos_controller.rb
class AmbitosController < ApplicationController
  # GET /ambitos
  # GET /ambitos.xml
  def index
    @ambitos = Ambito.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ambitos }
    end
  end

  # GET /ambitos/1
  # GET /ambitos/1.xml
  def show
    @ambito = Ambito.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ambito }
    end
  end

  # GET /ambitos/new
  # GET /ambitos/new.xml
  def new
    @ambito = Ambito.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ambito }
    end
  end

  # GET /ambitos/1/edit
  def edit
    @ambito = Ambito.find(params[:id])
  end

  # POST /ambitos
  # POST /ambitos.xml
  def create
    @ambito = Ambito.new(params[:ambito])

    respond_to do |format|
      if @ambito.save
        format.html { redirect_to(@ambito, :notice => 'Ambito was successfully created.') }
        format.xml  { render :xml => @ambito, :status => :created, :location => @ambito }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ambito.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ambitos/1
  # PUT /ambitos/1.xml
  def update
    @ambito = Ambito.find(params[:id])

    respond_to do |format|
      if @ambito.update_attributes(params[:ambito])
        format.html { redirect_to(@ambito, :notice => 'Ambito was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ambito.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ambitos/1
  # DELETE /ambitos/1.xml
  def destroy
    @ambito = Ambito.find(params[:id])
    @ambito.destroy

    respond_to do |format|
      format.html { redirect_to(ambitos_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lugars_controller.rb
class LugarsController < ApplicationController
  # GET /lugars
  # GET /lugars.xml
  def index
    @lugars = Lugar.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lugars }
    end
  end

  # GET /lugars/1
  # GET /lugars/1.xml
  def show
    @lugar = Lugar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lugar }
    end
  end

  # GET /lugars/new
  # GET /lugars/new.xml
  def new
    @lugar = Lugar.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lugar }
    end
  end

  # GET /lugars/1/edit
  def edit
    @lugar = Lugar.find(params[:id])
  end

  # POST /lugars
  # POST /lugars.xml
  def create
    @lugar = Lugar.new(params[:lugar])

    respond_to do |format|
      if @lugar.save
        format.html { redirect_to(@lugar, :notice => 'Lugar was successfully created.') }
        format.xml  { render :xml => @lugar, :status => :created, :location => @lugar }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lugar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lugars/1
  # PUT /lugars/1.xml
  def update
    @lugar = Lugar.find(params[:id])

    respond_to do |format|
      if @lugar.update_attributes(params[:lugar])
        format.html { redirect_to(@lugar, :notice => 'Lugar was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lugar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lugars/1
  # DELETE /lugars/1.xml
  def destroy
    @lugar = Lugar.find(params[:id])
    @lugar.destroy

    respond_to do |format|
      format.html { redirect_to(lugars_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/normas_controller.rb
class NormasController < ApplicationController
  # GET /normas
  # GET /normas.xml
  def index
    @normas = Norma.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @normas }
    end
  end

  # GET /normas/1
  # GET /normas/1.xml
  def show
    @norma = Norma.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @norma }
    end
  end

  # GET /normas/new
  # GET /normas/new.xml
  def new
    @norma = Norma.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @norma }
    end
  end

  # GET /normas/1/edit
  def edit
    @norma = Norma.find(params[:id])
  end

  # POST /normas
  # POST /normas.xml
  def create
    @norma = Norma.new(params[:norma])

    respond_to do |format|
      if @norma.save
        format.html { redirect_to(@norma, :notice => 'Norma was successfully created.') }
        format.xml  { render :xml => @norma, :status => :created, :location => @norma }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @norma.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /normas/1
  # PUT /normas/1.xml
  def update
    @norma = Norma.find(params[:id])

    respond_to do |format|
      if @norma.update_attributes(params[:norma])
        format.html { redirect_to(@norma, :notice => 'Norma was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @norma.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /normas/1
  # DELETE /normas/1.xml
  def destroy
    @norma = Norma.find(params[:id])
    @norma.destroy

    respond_to do |format|
      format.html { redirect_to(normas_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ambitos_helper.rb
module AmbitosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lugars_helper.rb
module LugarsHelper
end

app/helpers/normas_helper.rb
module NormasHelper
end

app/views/ambitos/_form.html.erb
<%= form_for(@ambito) do |f| %>
  <% if @ambito.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ambito.errors.count, "error") %> prohibited this ambito from being saved:</h2>

      <ul>
      <% @ambito.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ambitos/edit.html.erb
<h1>Editing ambito</h1>

<%= render 'form' %>

<%= link_to 'Show', @ambito %> |
<%= link_to 'Back', ambitos_path %>

app/views/ambitos/index.html.erb
<h1>Listing ambitos</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ambitos.each do |ambito| %>
  <tr>
    <td><%= ambito.name %></td>
    <td><%= link_to 'Show', ambito %></td>
    <td><%= link_to 'Edit', edit_ambito_path(ambito) %></td>
    <td><%= link_to 'Destroy', ambito, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ambito', new_ambito_path %>

app/views/ambitos/new.html.erb
<h1>New ambito</h1>

<%= render 'form' %>

<%= link_to 'Back', ambitos_path %>

app/views/ambitos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @ambito.name %>
</p>


<%= link_to 'Edit', edit_ambito_path(@ambito) %> |
<%= link_to 'Back', ambitos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infolegal</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lugars/_form.html.erb
<%= form_for(@lugar) do |f| %>
  <% if @lugar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lugar.errors.count, "error") %> prohibited this lugar from being saved:</h2>

      <ul>
      <% @lugar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lugars/edit.html.erb
<h1>Editing lugar</h1>

<%= render 'form' %>

<%= link_to 'Show', @lugar %> |
<%= link_to 'Back', lugars_path %>

app/views/lugars/index.html.erb
<h1>Listing lugars</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lugars.each do |lugar| %>
  <tr>
    <td><%= lugar.name %></td>
    <td><%= link_to 'Show', lugar %></td>
    <td><%= link_to 'Edit', edit_lugar_path(lugar) %></td>
    <td><%= link_to 'Destroy', lugar, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lugar', new_lugar_path %>

app/views/lugars/new.html.erb
<h1>New lugar</h1>

<%= render 'form' %>

<%= link_to 'Back', lugars_path %>

app/views/lugars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lugar.name %>
</p>


<%= link_to 'Edit', edit_lugar_path(@lugar) %> |
<%= link_to 'Back', lugars_path %>

app/views/normas/_form.html.erb
<%= form_for(@norma) do |f| %>
  <% if @norma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@norma.errors.count, "error") %> prohibited this norma from being saved:</h2>

      <ul>
      <% @norma.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :norma %><br />
    <%= f.text_field :norma %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :resumen %><br />
    <%= f.text_field :resumen %>
  </div>
  <div class="field">
    <%= f.label :notas %><br />
    <%= f.text_field :notas %>
  </div>
  <div class="field">
    <%= f.label :lugar_id %><br />
    <%= f.text_field :lugar_id %>
  </div>
  <div class="field">
    <%= f.label :ambito_id %><br />
    <%= f.text_field :ambito_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/normas/edit.html.erb
<h1>Editing norma</h1>

<%= render 'form' %>

<%= link_to 'Show', @norma %> |
<%= link_to 'Back', normas_path %>

app/views/normas/index.html.erb
<h1>Listing normas</h1>

<table>
  <tr>
    <th>Norma</th>
    <th>Titulo</th>
    <th>Resumen</th>
    <th>Notas</th>
    <th>Lugar</th>
    <th>Ambito</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @normas.each do |norma| %>
  <tr>
    <td><%= norma.norma %></td>
    <td><%= norma.titulo %></td>
    <td><%= norma.resumen %></td>
    <td><%= norma.notas %></td>
    <td><%= norma.lugar_id %></td>
    <td><%= norma.ambito_id %></td>
    <td><%= link_to 'Show', norma %></td>
    <td><%= link_to 'Edit', edit_norma_path(norma) %></td>
    <td><%= link_to 'Destroy', norma, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Norma', new_norma_path %>

app/views/normas/new.html.erb
<h1>New norma</h1>

<%= render 'form' %>

<%= link_to 'Back', normas_path %>

app/views/normas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Norma:</b>
  <%= @norma.norma %>
</p>

<p>
  <b>Titulo:</b>
  <%= @norma.titulo %>
</p>

<p>
  <b>Resumen:</b>
  <%= @norma.resumen %>
</p>

<p>
  <b>Notas:</b>
  <%= @norma.notas %>
</p>

<p>
  <b>Lugar:</b>
  <%= @norma.lugar_id %>
</p>

<p>
  <b>Ambito:</b>
  <%= @norma.ambito_id %>
</p>


<%= link_to 'Edit', edit_norma_path(@norma) %> |
<%= link_to 'Back', normas_path %>